"""
This script serves as the second step in a data processing pipeline for whole-slide images (WSIs).
It takes a CSV file generated by a previous script (which maps original slides to their
extracted label and macro images) and enriches it by performing Optical Character Recognition (OCR)
on these images.

The script is designed to be robust and efficient:
- It uses Surya OCR for text extraction, with GPU acceleration when available.
- It handles file paths intelligently, resolving them relative to the input CSV's location.
- Parallel processing is implemented using a thread pool to speed up the OCR task.
- A progress bar provides real-time feedback on the processing status.

The output is a new, enriched CSV file containing all the original data plus new columns for the
extracted text from both label and macro images, and a flag indicating if the row was
successfully processed by OCR.
"""

# ==============================================================================
# 1. IMPORTS
# ==============================================================================
import argparse
import csv
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import torch
from PIL import Image, UnidentifiedImageError
from tqdm import tqdm

from surya.ocr import run_ocr
from surya.model.detection.model import load_model as load_det_model, load_processor as load_det_processor
from surya.model.recognition.model import load_model as load_rec_model
from surya.model.recognition.processor import load_processor as load_rec_processor



# ==============================================================================
# 2. CONFIGURATION
# ==============================================================================

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


# ==============================================================================
# 3. HELPER FUNCTIONS
# ==============================================================================

def clean_and_resolve_path(path_str: str) -> Path | None:
    """
    Cleans a potentially messy path string and resolves it to an absolute Path object.

    Handles path inconsistencies such as different slash types or relative path prefixes.

    Args:
        path_str: The input path string, which might contain backslashes or './'.

    Returns:
        A resolved, absolute Path object if the input string is not empty, otherwise None.
    """
    if not path_str:
        return None

    cleaned_str = path_str.replace("\\", "/")
    if cleaned_str.startswith("./"):
        cleaned_str = cleaned_str[2:]

    return Path(cleaned_str).resolve()


def _extract_text_from_prediction(prediction_result, context: str) -> str:
    """
    Safely extracts concatenated text from a Surya OCR prediction result.

    This consolidates all the defensive checks needed when parsing Surya's output
    into a single reusable function.

    Args:
        prediction_result: The raw return value from RecognitionPredictor.__call__.
        context: A descriptive string (e.g. "label for patient X") used in log messages.

    Returns:
        The extracted text as a single string joined by spaces, or an error/status
        sentinel string if extraction fails at any stage.
    """
    if prediction_result is None:
        logger.warning(f"Predictor returned None for {context}.")
        return ""

    if not isinstance(prediction_result, list) or len(prediction_result) == 0:
        logger.warning(
            f"Predictor returned non-list or empty list for {context}. "
            f"Value: {prediction_result}"
        )
        return ""

    page_result = prediction_result[0]
    if page_result is None:
        logger.warning(f"Prediction result element [0] is None for {context}.")
        return ""

    if not hasattr(page_result, "text_lines"):
        logger.warning(
            f"Prediction object for {context} missing 'text_lines' attribute."
        )
        return ""

    text_lines = page_result.text_lines
    if not text_lines:  # Covers both None and empty list
        logger.info(f"No text detected for {context}.")
        return ""

    # Extract text from each line object, guarding against malformed entries.
    lines = [line.text for line in text_lines if hasattr(line, "text") and line.text]
    return " ".join(lines)


def perform_ocr_on_row(
    row: dict,
    csv_dir: Path,
    det_model,
    det_processor,
    rec_model,
    rec_processor,
) -> dict:
    """
    Performs Surya OCR on the label and macro images for a single CSV row.

    This function is designed to be executed in a separate thread. It handles path
    resolution, image loading, OCR execution, and error handling for one data entry.

    Args:
        row: A dictionary representing one row from the input CSV.
        csv_dir: The parent directory of the input CSV file.
        det_model: The initialized Surya detection model.
        det_processor: The initialized Surya detection processor.
        rec_model: The initialized Surya recognition model.
        rec_processor: The initialized Surya recognition processor.
    Returns:
        The original row dictionary updated with 'label_text', 'macro_text',
        and 'ocr_qc_needed' fields.
    """
    updated_row = row.copy()
    label_text = ""
    macro_text = ""
    ocr_qc_needed = False

    # --- Resolve and Validate Image Paths ---
    label_path_str = row.get("label_path")
    macro_path_str = row.get("macro_path")

    paths_to_process: dict[str, Path] = {}
    if label_path_str:
        label_path = clean_and_resolve_path(label_path_str)
        if label_path and label_path.exists():
            paths_to_process["label"] = label_path
        else:
            logger.warning(
                f"Label image not found at resolved path '{label_path}' "
                f"for slide '{row.get('original_slide_path', 'unknown')}'"
            )

    if macro_path_str:
        macro_path = clean_and_resolve_path(macro_path_str)
        if macro_path and macro_path.exists():
            paths_to_process["macro"] = macro_path
        else:
            logger.warning(
                f"Macro image not found at resolved path '{macro_path}' "
                f"for slide '{row.get('original_slide_path', 'unknown')}'"
            )

    slide_id = row.get("original_slide_path", "unknown")

    if paths_to_process:
        try:
            # --- Process Label Image ---
            if "label" in paths_to_process:
                try:
                    img_label = Image.open(paths_to_process["label"]).convert("RGB")
                    predictions = run_ocr([img_label], [["en"]], det_model, det_processor, rec_model, rec_processor)
                    label_text = _extract_text_from_prediction(
                        predictions, f"label for '{slide_id}'"
                    )
                except UnidentifiedImageError:
                    logger.error(
                        f"Cannot identify/open label image (corrupted?): "
                        f"{paths_to_process['label']}"
                    )
                except Exception as e:
                    logger.error(
                        f"Failed OCR on label for '{slide_id}': "
                        f"{type(e).__name__}: {e}"
                    )

            # --- Process Macro Image ---
            if "macro" in paths_to_process:
                try:
                    img_macro = Image.open(paths_to_process["macro"]).convert("RGB")

                    # Rotate 90° clockwise — text on macro images is often sideways.
                    img_macro = img_macro.rotate(-90, expand=True)

                    # Crop to the half most likely to contain text.
                    width, height = img_macro.size
                    crop_box = (
                        (0, 0, width // 2, height)
                        if width > height
                        else (0, 0, width, height // 2)
                    )
                    img_macro = img_macro.crop(crop_box)

                    predictions = run_ocr([img_macro], [["en"]], det_model, det_processor, rec_model, rec_processor)
                    macro_text = _extract_text_from_prediction(
                        predictions, f"macro for '{slide_id}'"
                    )
                except UnidentifiedImageError:
                    logger.error(
                        f"Cannot identify/open macro image (corrupted?): "
                        f"{paths_to_process['macro']}"
                    )
                except Exception as e:
                    logger.error(
                        f"Failed OCR on macro for '{slide_id}': "
                        f"{type(e).__name__}: {e}"
                    )

            # If we got here without a top-level crash, mark the row as processed.
            ocr_qc_needed = True

        except Exception as e:
            logger.error(
                f"Unexpected failure processing row for slide '{slide_id}': {e}"
            )
            ocr_qc_needed = False

    # --- Update the row with OCR results ---
    updated_row["label_text"] = label_text
    updated_row["macro_text"] = macro_text
    updated_row["ocr_qc_needed"] = ocr_qc_needed

    return updated_row


# ==============================================================================
# 4. MAIN ORCHESTRATION FUNCTION
# ==============================================================================

def add_ocr_to_mapping(
    mapping_csv: Path,
    output_csv: Path,
    num_workers: int,
):
    """
    Reads a mapping CSV, orchestrates Surya OCR for all rows using a thread pool,
    and writes the enriched data to a new CSV file.

    Args:
        mapping_csv: Path to the input CSV file.
        output_csv: Path where the enriched output CSV will be saved.
        num_workers: The number of concurrent threads to use for OCR processing.
    """
    if not mapping_csv.exists():
        logger.error(f"Input mapping CSV not found: {mapping_csv}")
        return

    # --- Initialize Surya models (once, shared across all workers) ---
    device = "cuda" if torch.cuda.is_available() else "cpu"
    logger.info(f"Torch device: {device}")

    logger.info("Loading Surya detection model...")
    det_model = load_det_model()
    det_processor = load_det_processor()
    logger.info("Loading Surya recognition model...")
    rec_model = load_rec_model()
    rec_processor = load_rec_processor()
    logger.info("Surya models loaded successfully.")

    # Read the entire CSV into a list of dictionaries.
    with open(mapping_csv, "r", encoding="utf-8") as f:
        reader_csv = csv.DictReader(f)
        rows = list(reader_csv)

    if not rows:
        logger.warning("Input CSV is empty. Nothing to process.")
        return

    logger.info(f"Loaded {len(rows)} rows from '{mapping_csv}'.")

    updated_rows: list[dict] = []
    csv_dir = mapping_csv.parent

    with ThreadPoolExecutor(max_workers=num_workers) as executor:
        future_to_row = {
            executor.submit(
                perform_ocr_on_row, row, csv_dir,
                det_model, det_processor, rec_model, rec_processor,
            ): row
            for row in rows
        }

        progress_bar = tqdm(
            as_completed(future_to_row), total=len(rows), desc="Running Surya OCR"
        )
        for future in progress_bar:
            try:
                updated_rows.append(future.result())
            except Exception as e:
                # Log but don't crash — the row will simply be missing from output.
                original_row = future_to_row[future]
                logger.error(
                    f"Worker thread crashed for slide "
                    f"'{original_row.get('original_slide_path', 'unknown')}': {e}"
                )

    if not updated_rows:
        logger.error("Processing failed catastrophically. No rows were updated.")
        return

    # --- Write the updated data to the new CSV file ---
    headers = list(updated_rows[0].keys())

    logger.info(f"Writing {len(updated_rows)} enriched rows to {output_csv}...")
    try:
        with open(output_csv, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=headers)
            writer.writeheader()
            writer.writerows(updated_rows)
        logger.info("Successfully created enriched CSV.")
    except Exception as e:
        logger.error(f"Failed to write the output CSV file: {e}")


# ==============================================================================
# 5. SCRIPT EXECUTION
# ==============================================================================

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Enrich a slide mapping CSV with OCR text from label and macro "
                    "images using Surya OCR."
    )
    parser.add_argument(
        "--mapping_csv",
        type=Path,
        required=True,
        help="Path to the input CSV file generated by the first script "
             "(e.g., slide_mapping.csv).",
    )
    parser.add_argument(
        "--output_csv",
        type=Path,
        required=True,
        help="Path to save the new CSV file with added OCR columns.",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=1,
        help="Number of worker threads for parallel processing. "
             "Default is 1 to avoid GPU contention with Surya.",
    )
    args = parser.parse_args()

    # Ensure the directory for the output file exists.
    args.output_csv.parent.mkdir(parents=True, exist_ok=True)

    add_ocr_to_mapping(args.mapping_csv, args.output_csv, args.workers)
