"""
This script serves as the second step in a data processing pipeline for whole-slide images (WSIs).
It takes a CSV file generated by a previous script (which maps original slides to their
extracted label and macro images) and enriches it by performing Optical Character Recognition (OCR)
on these images.

The script is designed to be robust and efficient:
- It uses Tesseract OCR for text extraction.
- It handles file paths intelligently, resolving them relative to the input CSV's location.
- Parallel processing is implemented using a thread pool to speed up the OCR task.
- A progress bar provides real-time feedback on the processing status.

The output is a new, enriched CSV file containing all the original data plus new columns for the
extracted text from both label and macro images, and a flag indicating if the row was
successfully processed by OCR.
"""

# ==============================================================================
# 1. IMPORTS
# ==============================================================================
import argparse
import csv
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import cv2
import numpy as np
import pytesseract
from PIL import Image, UnidentifiedImageError
from tqdm import tqdm


# ==============================================================================
# 2. CONFIGURATION
# ==============================================================================

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


# ==============================================================================
# 3. HELPER FUNCTIONS
# ==============================================================================

def clean_and_resolve_path(path_str: str) -> Path | None:
    """
    Cleans a potentially messy path string and resolves it to an absolute Path object.

    This function is designed to handle path inconsistencies, such as different
    slash types or relative path prefixes, making file access more reliable.

    Args:
        path_str (str): The input path string, which might contain backslashes or './'.

    Returns:
        Path | None: A resolved, absolute Path object if the input string is not empty,
                     otherwise None.
    """
    if not path_str:
        return None

    # 1. Standardize path separators to forward slashes, which work across platforms.
    cleaned_str = path_str.replace("\\", "/")

    # 2. Create a Path object
    # WARNING: this assumes that cleaned_str is an absolute path, which should be the case
    cleaned_path = Path(cleaned_str)
    print(f"{cleaned_path}")
    return Path(cleaned_str)


def preprocess_image_for_ocr(image_np: np.ndarray) -> np.ndarray:
    """Convert to grayscale and apply Otsu's binarization to improve OCR accuracy."""
    gray = cv2.cvtColor(image_np, cv2.COLOR_RGB2GRAY)
    _, binary = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    return binary


def ocr_all_rotations(image_np: np.ndarray, lang: str) -> str:
    """
    Run Tesseract OCR at 0°, 90°, 180°, and 270° rotations and return all
    extracted text concatenated, mirroring EasyOCR's rotation_info behaviour.
    """
    rotations = [
        cv2.ROTATE_90_CLOCKWISE,
        cv2.ROTATE_180,
        cv2.ROTATE_90_COUNTERCLOCKWISE,
    ]
    results = [pytesseract.image_to_string(image_np, lang=lang).strip()]
    for rot in rotations:
        rotated = cv2.rotate(image_np, rot)
        results.append(pytesseract.image_to_string(rotated, lang=lang).strip())
    return " ".join(r for r in results if r)


def perform_ocr_on_row(
    row: dict,
    csv_dir: Path,
    langs: str = "eng",
) -> dict:
    """
    Performs Tesseract OCR on the label and macro images for a single CSV row.

    This function is designed to be executed in a separate thread. It handles path
    resolution, image loading, OCR execution, and error handling for one data entry.

    Args:
        row: A dictionary representing one row from the input CSV.
        csv_dir: The parent directory of the input CSV file.
        langs: Language string for Tesseract OCR (e.g. 'eng').

    Returns:
        The original row dictionary updated with 'label_text', 'macro_text',
        and 'ocr_qc_needed' fields.
    """
    updated_row = row.copy()
    label_text = ""
    macro_text = ""
    ocr_qc_needed = False

    # --- Resolve and Validate Image Paths ---
    label_path_str = row.get("label_path")
    macro_path_str = row.get("macro_path")

    paths_to_process: dict[str, Path] = {}
    if label_path_str:
        label_path = clean_and_resolve_path(label_path_str)
        if label_path and label_path.exists():
            paths_to_process["label"] = label_path
            # Strip csv_dir from label_path for the flask app
            updated_row["label_path"] = label_path.relative_to(csv_dir)
        else:
            logger.warning(
                f"Label image not found at resolved path '{label_path}' "
                f"for slide '{row.get('original_slide_path', 'unknown')}'"
            )

    if macro_path_str:
        macro_path = clean_and_resolve_path(macro_path_str)
        if macro_path and macro_path.exists():
            paths_to_process["macro"] = macro_path
            # Strip csv_dir from macro_path for the flask app
            updated_row["macro_path"] = macro_path.relative_to(csv_dir)
        else:
            logger.warning(
                f"Macro image not found at resolved path '{macro_path}' "
                f"for slide '{row.get('original_slide_path', 'unknown')}'"
            )

    # Also strip csv_dir from thumbnail_path for the flask app
    thumbnail_path = clean_and_resolve_path(row.get("thumbnail_path"))
    updated_row["thumbnail_path"] = thumbnail_path.relative_to(csv_dir)

    slide_id = row.get("original_slide_path", "unknown")

    if paths_to_process:
        try:
            # --- Process Label Image ---
            if "label" in paths_to_process:
                try:
                    img_label = Image.open(paths_to_process["label"]).convert("RGB")
                    img_label_np = preprocess_image_for_ocr(np.array(img_label))
                    label_text = pytesseract.image_to_string(img_label_np, lang=langs).strip()
                    logger.info(f"Successfully ran OCR on label for '{slide_id}'")
                except UnidentifiedImageError:
                    logger.error(
                        f"Cannot identify/open label image (corrupted?): "
                        f"{paths_to_process['label']}"
                    )
                except Exception as e:
                    logger.error(
                        f"Failed OCR on label for '{slide_id}': "
                        f"{type(e).__name__}: {e}"
                    )

            # --- Process Macro Image ---
            if "macro" in paths_to_process:
                try:
                    img_macro = Image.open(paths_to_process["macro"]).convert("RGB")

                    # Rotate 90° clockwise — text on macro images is often sideways.
                    img_macro = img_macro.rotate(-90, expand=True)

                    # Crop to the half most likely to contain text.
                    width, height = img_macro.size
                    crop_box = (
                        (0, 0, width // 2, height)
                        if width > height
                        else (0, 0, width, height // 2)
                    )
                    img_macro = img_macro.crop(crop_box)

                    img_macro_np = preprocess_image_for_ocr(np.array(img_macro))
                    macro_text = ocr_all_rotations(img_macro_np, lang=langs)
                    logger.info(f"Successfully ran OCR on macro for '{slide_id}'")
                except UnidentifiedImageError:
                    logger.error(
                        f"Cannot identify/open macro image (corrupted?): "
                        f"{paths_to_process['macro']}"
                    )
                except Exception as e:
                    logger.error(
                        f"Failed OCR on macro for '{slide_id}': "
                        f"{type(e).__name__}: {e}"
                    )

            # If we got here without a top-level crash, mark the row as processed.
            ocr_qc_needed = True

        except Exception as e:
            logger.error(
                f"Unexpected failure processing row for slide '{slide_id}': {e}"
            )
            ocr_qc_needed = False

    # --- Update the row with OCR results ---
    # To clean up newlines often introduced by Tesseract
    updated_row["label_text"] = " ".join(label_text.splitlines()) if label_text else ""
    updated_row["macro_text"] = " ".join(macro_text.splitlines()) if macro_text else ""
    updated_row["ocr_qc_needed"] = ocr_qc_needed

    return updated_row


# ==============================================================================
# 4. MAIN ORCHESTRATION FUNCTION
# ==============================================================================

def add_ocr_to_mapping(
    mapping_csv: Path,
    output_csv: Path,
    num_workers: int = 4,
    langs: str = "eng",
):
    """
    Reads a mapping CSV, orchestrates Tesseract OCR for all rows using a thread pool,
    and writes the enriched data to a new CSV file.

    Args:
        mapping_csv: Path to the input CSV file.
        output_csv: Path where the enriched output CSV will be saved.
        num_workers: The number of concurrent threads to use for OCR processing.
        langs: Language string for OCR (e.g. 'eng').
    """
    if not mapping_csv.exists():
        logger.error(f"Input mapping CSV not found: {mapping_csv}")
        return

    # Read the entire CSV into a list of dictionaries.
    with open(mapping_csv, "r", encoding="utf-8") as f:
        reader_csv = csv.DictReader(f)
        rows = list(reader_csv)

    if not rows:
        logger.warning("Input CSV is empty. Nothing to process.")
        return

    logger.info(f"Loaded {len(rows)} rows from '{mapping_csv}'.")

    updated_rows: list[dict] = []
    csv_dir = mapping_csv.parent

    with ThreadPoolExecutor(max_workers=num_workers) as executor:
        future_to_row = {
            executor.submit(
                perform_ocr_on_row, row, csv_dir, langs
            ): row
            for row in rows
        }

        progress_bar = tqdm(
            as_completed(future_to_row), total=len(rows), desc="Running Tesseract OCR"
        )
        for future in progress_bar:
            try:
                updated_rows.append(future.result())
            except Exception as e:
                # Log but don't crash — the row will simply be missing from output.
                original_row = future_to_row[future]
                logger.error(
                    f"Worker thread crashed for slide "
                    f"'{original_row.get('original_slide_path', 'unknown')}': {e}"
                )

    if not updated_rows:
        logger.error("Processing failed catastrophically. No rows were updated.")
        return

    # --- Write the updated data to the new CSV file ---
    headers = list(updated_rows[0].keys())

    logger.info(f"Writing {len(updated_rows)} enriched rows to {output_csv}...")
    try:
        with open(output_csv, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=headers)
            writer.writeheader()
            writer.writerows(updated_rows)
        logger.info("Successfully created enriched CSV.")
    except Exception as e:
        logger.error(f"Failed to write the output CSV file: {e}")


# ==============================================================================
# 5. SCRIPT EXECUTION
# ==============================================================================

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Enrich a slide mapping CSV with OCR text from label and macro "
                    "images using Tesseract OCR."
    )
    parser.add_argument(
        "--mapping_csv",
        type=Path,
        required=True,
        help="Path to the input CSV file generated by the first script "
             "(e.g., slide_mapping.csv).",
    )
    parser.add_argument(
        "--output_csv",
        type=Path,
        required=True,
        help="Path to save the new CSV file with added OCR columns.",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=4,
        help="Number of worker threads for parallel processing. "
             "Default is 4.",
    )
    parser.add_argument(
        "--langs",
        type=str,
        default="eng",
        help="Language for Tesseract OCR (e.g. 'eng').",
    )

    args = parser.parse_args()

    # Ensure the directory for the output file exists.
    args.output_csv.parent.mkdir(parents=True, exist_ok=True)

    add_ocr_to_mapping(args.mapping_csv, args.output_csv, args.workers, args.langs)
