"""
This script takes an input CSV file produced from the Label-Check pipeline (post-QC), extracts the accession ID, stain, block number, and original file paths, and creates new file paths according to guidelines in IuCompPath/Wiki/Digital_Pathology/Database_construction_and_management/PseudoID_conventions.md.

Organ type is a mandatory argument (--organ) and will be used to rename all of the slides in the input CSV.

Image type and sample acquistion type are generically left as WSI and RE (resection), respectively, unless a CSV of CoPath data obtained via the SQL query scripts generated by IuCompPath/copath_report_utils is provided; in this case, slides are also renamed with the accession date and sample acquistion type indicated in the --copath-data CSV.

Unless the --dry-run flag is provided, this script renames the original files to the newly-generated file paths. Whether or not the --dry-run flag is provided, both the original and new file paths are output in post_qc.csv.
"""

import argparse
import datetime
import re
import sys
from pathlib import Path

import pandas as pd


REQUIRED_COPATH_HEADERS = [ 
     "accession_date",
     "sample_acquisition_type",
]

# input CSV must contain at least one of these
ADDITIONAL_SAMP_ACQ_FIELDS = [
    "report",
    "final_diagnosis",
    "addendum_diagnosis",
]


class PID:
    pid = 'AAAAA@'
    prev = {}

    def __init__(self, instance):
        self.instance = instance


def assign_pid(x: str) -> str:
    pid = PID.pid

    if x not in PID.prev:
        reverse = list(pid[::-1])
        for i in range(len(reverse)):
            cur = reverse[i]
            if cur == 'Z':
                reverse[i] = 'A'
            else:
                reverse[i] = chr(ord(cur) + 1)
                break
        reverse = "".join(reverse)
        pid = reverse[::-1]
        PID.pid = pid
        PID.prev[x] = pid
        print(f"\tAssigned {pid} to {x}")
    else:
        print(f"\tPID for {x} = {pid}")

    return PID.prev[x]


def clean_acc_date(acc_date: str) -> str:
    try:
        parsed = datetime.date.strptime(acc_date, "%Y-%m-%d %H:%M:%S.%f")
    except ValueError as ve:
        print(f"Error: could not convert {acc_date} to datetime")
        return "XXXXXXXX"

    return parsed.strftime("%Y%m%d")


def identify_samp_acq(samp_acq: str) -> str:
    resection_match = re.search(r"resection", samp_acq, flags=re.IGNORECASE)
    if resection_match:
        return "RE"

    biopsy_match = re.search(r"biopsy", samp_acq, flags=re.IGNORECASE)
    if biopsy_match:
        return "BP"

    return "XX"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Rename files using CSV produced from the fourth step of the Label-Check pipeline (app.py)"
    )
    parser.add_argument(
        "input_csv",
        type=Path,
        help="CSV produced by step three of Label-Check pipeline and edited by step four (QC)",
    )
    parser.add_argument(
        "--organ",
        type=str,
        required=True,
        help="Organ from which originate all of the slides in the input CSV (e.g. 'BRAIN', 'breast', 'Testes')",
    )
    parser.add_argument(
        "--copath-data",
        type=Path,
        help="Optional CSV of patient data obtained from CoPath SQL query scripts; will rename slides with accession date and sample acquistion type",
    )
    parser.add_argument(
        "--start-after",
        type=str,
        help="The PID which the renaming should start after (defaults to AAAAA@ [first assigned PID will be AAAAAA])"
    )
    parser.add_argument(
        "--dry-run",
        required=False,
        help="Conduct a 'dry run', where files are only renamed in the output csv (post_qc.csv)",
        action="store_true"
    )

    args = parser.parse_args()
    
    # is the same for all slides in the input CSV
    organ = args.organ.upper()

    copath_data = None
    if args.copath_data is not None:
        try:
            data_pd = pd.read_csv(args.copath_data, dtype=str)
        except Exception as e:
            print(f"Error opening {args.copath_data}: {e}")
            sys.exit(1)
        
        columns = data_pd.columns

        if "accession_id" not in columns:
            print(f"Error: {args.copath_data} has no 'accession_id' column")
            sys.exit(1)
        if "accession_date" not in columns:
            print(f"Error: {args.copath_data} has no 'accession_date' column")
            sys.exit(1)
        if "sample_acquisition_type" not in columns:
            print(f"Error: {args.copath_data} has no 'sample_acquisition_type' column")
            sys.exit(1)

        additional_fields = []
        for other in ADDITIONAL_SAMP_ACQ_FIELDS:
            if other in columns:
                additional_fields.append(other)

        if len(additional_fields) == 0:
            print(f"Error: at least one of these report fields is required: {ADDITIONAL_SAMP_ACQ_FIELDS}")

        copath_data = {}
        for i in range(len(data_pd)):
            acc = data_pd.loc[i, "accession_id"]
            if acc is None or acc == "" or isinstance(acc, float):
                continue

            acc_date = data_pd.loc[i, "accession_date"]
            samp_acq_fields = data_pd.loc[i, "sample_acquisition_type"]
            for add_field in additional_fields:
                report_field = data_pd.loc[i, add_field]
                if isinstance(report_field, str):
                    samp_acq_fields += report_field

            acc_dict = {}
            acc_dict["acc_date"] = clean_acc_date(acc_date)
            acc_dict["samp_acq"] = identify_samp_acq(samp_acq_fields)

            copath_data[acc] = acc_dict

    start_after = args.start_after
    if start_after:
        print(f"Starting after {start_after}")
        PID.pid = start_after

    dry_run = args.dry_run
    if dry_run:
        print("\x1b[1mExecuting dry run; no files will be renamed.\x1b[0m\n")

    post_qc = pd.read_csv(args.input_csv, dtype=str)

    fields = ['AccessionID', 'Stain', 'BlockNumber', 'original_slide_path']

    # check that input CSV has the above columns and populate the new CSV with these columns
    final = pd.DataFrame()
    for i in range(len(fields)):
        f = fields[i]
        if f not in post_qc.columns:
            print(f"ERR: input CSV does not have a {f} field")
            print("Make sure that your CSV has been produced by the Label-Check pipeline and edited via the flask app")
            sys.exit(1)

        final.insert(i, fields[i], post_qc.pop(fields[i]))

    # create new paths
    final.insert(final.columns.get_loc('original_slide_path') + 1, 'new_slide_path', None)
    num_changed = 0
    unique_names = {}
    for i in range(len(final)):
        orig = final.loc[i, 'original_slide_path']
        if isinstance(orig, float):
            continue

        print(f"Renaming {orig}:")
        # generate PID and assign organ type;
        # for now, organ type in this script is determined by whether the accession ID
        # has NP or A at the beginning; if yes, organ is BRAIN, if no, organ is unlabelled
        a_id = final.loc[i, 'AccessionID']
        if not isinstance(a_id, str):
            print(f"\tERR: {a_id} is not a str; cannot assign PID")
            final.loc[i, 'PID'] = "XXXXXX"
            continue

        pid = assign_pid(a_id)
        final.loc[i, 'PID'] = pid

        o_path = Path(final.loc[i, 'original_slide_path'])
        o_parent = o_path.parent
        o_ext = o_path.suffix
        
        stain = final.loc[i, 'Stain']
        block = final.loc[i, 'BlockNumber']

        # if no stain or block, replace with "XX"
        if not isinstance(stain, str):
            print(f"	ERR: stain for {pid} is not a string; cannot rename file")
            continue
        elif '$' in stain:
            stain = "XX"

        if not isinstance(block, str):
            print(f"	ERR: block number for {pid} is not a string; cannot rename file")
            continue
        elif '#' in stain:
            block = "XX"
       
        acc_date = "XXXXXXXX"
        timepoint = "XXXX"
        image_type = "WSI"
        samp_acq = "XX"

        if copath_data is not None:
            if a_id in copath_data.keys():
                slide_data = copath_data[a_id]
                acc_date = slide_data["acc_date"]
                samp_acq = slide_data["samp_acq"]

        cur_name = f"{organ}_{pid}_{acc_date}_{timepoint}_{stain}_{image_type}_{samp_acq}{block}"
        if cur_name in unique_names:
            unique_names[cur_name] += 1
        else:
            unique_names[cur_name] = 0
        section_count = unique_names[cur_name]
        new_name = f"{cur_name}{section_count:03d}{o_ext}"
        new_path = o_parent / new_name
       
        # make sure path exists before renaming
        if o_path.exists():
            # only rename if not a dry run
            if not dry_run:
                o_path.rename(new_path)
            num_changed += 1
            final.loc[i, 'new_slide_path'] = new_path
            print(f"\tRenamed {o_path} to {new_path}")
        else:
            # if the original path doesn't exist, record the new name anyway
            print(f"	ERR: {o_path} doesn't exist")
            final.loc[i, 'new_slide_path'] = new_name
            continue

    # write new CSV to post_qc.csv in the QC directory
    parent = args.input_csv.parent
    post_qc = parent / "post_qc.csv"
    final.to_csv(post_qc, index=False)
    print(f"\nChanged {num_changed} file paths")
    print(f"Wrote new CSV to {post_qc}")
